import { sidebar } from 'vuepress-theme-hope'

export const sidebarEn = sidebar({
  '/cli/': [
    {
      text: 'CLI',
      icon: 'iconfont icon-shell',
      children: [ '/cli/README.md' ],
    }, {
      text: 'Text Processing with GNU awk',
      collapsible: true,
      icon: 'iconfont icon-shell',
      children: [
        '/cli/text-processing-w-gnu-awk/README.md',
        '/cli/text-processing-w-gnu-awk/01-installation-and-documentation.md',
        '/cli/text-processing-w-gnu-awk/02-awk-introduction.md',
        '/cli/text-processing-w-gnu-awk/03-regular-expressions.md',
        '/cli/text-processing-w-gnu-awk/04-field-separators.md',
        '/cli/text-processing-w-gnu-awk/05-record-separators.md',
        '/cli/text-processing-w-gnu-awk/06-in-place-file-editing.md',
        '/cli/text-processing-w-gnu-awk/07-using-shell-variables.md',
        '/cli/text-processing-w-gnu-awk/08-control-structures.md',
        '/cli/text-processing-w-gnu-awk/09-built-in-functions.md',
        '/cli/text-processing-w-gnu-awk/10-multiple-file-input.md',
        '/cli/text-processing-w-gnu-awk/11-processing-multiple-records.md',
        '/cli/text-processing-w-gnu-awk/12-two-file-processing.md',
        '/cli/text-processing-w-gnu-awk/13-dealing-with-duplicates.md',
        '/cli/text-processing-w-gnu-awk/14-awk-scripts.md',
        '/cli/text-processing-w-gnu-awk/15-gotchas-and-tips.md',
        '/cli/text-processing-w-gnu-awk/16-further-reading.md',
      ],
    }, {
      text: 'Mastering Curl - Interactive Text Guide',
      collapsible: true,
      icon: 'iconfont icon-shell',
      children: [
        '/cli/mastering-curl-interactive-text-guide/README.md',
        '/cli/mastering-curl-interactive-text-guide/01-the-curl-project.md',
        '/cli/mastering-curl-interactive-text-guide/02-command-line-options.md',
        '/cli/mastering-curl-interactive-text-guide/03-urls.md',
        '/cli/mastering-curl-interactive-text-guide/04-curl-basics.md',
        '/cli/mastering-curl-interactive-text-guide/05-http.md'
      ]
    }, {
      text: 'Bash 쉘스크립트 개발 시작하기',
      collapsible: true,
      icon: 'iconfont icon-shell',
      children: [
        '/cli/bash-dev/README.md',
        '/cli/bash-dev/01.md',
        '/cli/bash-dev/02.md',
        '/cli/bash-dev/03.md',
        '/cli/bash-dev/04.md',
      ]
    }
  ], '/swift/' : [
    {
      text: 'Swift',
      icon: 'fa-brands fa-swift',
      children: [ '/swift/README.md' ]
    }, {
      text: '100 Days of Swift',
      collapsible: true,
      icon: 'fa-brands fa-swift',
      children: [
        '/swift/100-days-of-swift/README.md',
        '/swift/100-days-of-swift/01.md',
        '/swift/100-days-of-swift/02.md',
        '/swift/100-days-of-swift/03.md',
        '/swift/100-days-of-swift/04.md',
        '/swift/100-days-of-swift/05.md',
        '/swift/100-days-of-swift/06.md',
        '/swift/100-days-of-swift/07.md',
        '/swift/100-days-of-swift/08.md',
        '/swift/100-days-of-swift/09.md',
        '/swift/100-days-of-swift/10.md',
        '/swift/100-days-of-swift/11.md',
        '/swift/100-days-of-swift/12.md',
        '/swift/100-days-of-swift/13.md',
        '/swift/100-days-of-swift/14.md',
        '/swift/100-days-of-swift/15.md',
        '/swift/100-days-of-swift/16.md',
        '/swift/100-days-of-swift/17.md',
        '/swift/100-days-of-swift/18.md',
        '/swift/100-days-of-swift/19.md',
        '/swift/100-days-of-swift/20.md',
        '/swift/100-days-of-swift/21.md',
        '/swift/100-days-of-swift/22.md',
        '/swift/100-days-of-swift/23.md',
        '/swift/100-days-of-swift/24.md',
        '/swift/100-days-of-swift/25.md',
        '/swift/100-days-of-swift/26.md',
        '/swift/100-days-of-swift/27.md',
        '/swift/100-days-of-swift/28.md',
        '/swift/100-days-of-swift/29.md',
        '/swift/100-days-of-swift/30.md',
        '/swift/100-days-of-swift/31.md',
        '/swift/100-days-of-swift/32.md',
        '/swift/100-days-of-swift/33.md',
        '/swift/100-days-of-swift/34.md',
        '/swift/100-days-of-swift/35.md',
        '/swift/100-days-of-swift/36.md',
        '/swift/100-days-of-swift/37.md',
        '/swift/100-days-of-swift/38.md',
        '/swift/100-days-of-swift/39.md',
        '/swift/100-days-of-swift/40.md',
        '/swift/100-days-of-swift/41.md',
        '/swift/100-days-of-swift/42.md',
        '/swift/100-days-of-swift/43.md',
        '/swift/100-days-of-swift/44.md',
        '/swift/100-days-of-swift/45.md',
        '/swift/100-days-of-swift/46.md',
        '/swift/100-days-of-swift/47.md',
        '/swift/100-days-of-swift/48.md',
        '/swift/100-days-of-swift/49.md',
        '/swift/100-days-of-swift/50.md',
        '/swift/100-days-of-swift/51.md',
        '/swift/100-days-of-swift/52.md',
        '/swift/100-days-of-swift/53.md',
        '/swift/100-days-of-swift/54.md',
        '/swift/100-days-of-swift/55.md',
        '/swift/100-days-of-swift/56.md',
        '/swift/100-days-of-swift/57.md',
        '/swift/100-days-of-swift/58.md',
        '/swift/100-days-of-swift/59.md',
        '/swift/100-days-of-swift/60.md',
        '/swift/100-days-of-swift/61.md',
        '/swift/100-days-of-swift/62.md',
        '/swift/100-days-of-swift/63.md',
        '/swift/100-days-of-swift/64.md',
        '/swift/100-days-of-swift/65.md',
        '/swift/100-days-of-swift/66.md',
        '/swift/100-days-of-swift/67.md',
        '/swift/100-days-of-swift/68.md',
        '/swift/100-days-of-swift/69.md',
        '/swift/100-days-of-swift/70.md',
        '/swift/100-days-of-swift/71.md',
        '/swift/100-days-of-swift/72.md',
        '/swift/100-days-of-swift/73.md',
        '/swift/100-days-of-swift/74.md',
        '/swift/100-days-of-swift/75.md',
        '/swift/100-days-of-swift/76.md',
        '/swift/100-days-of-swift/77.md',
        '/swift/100-days-of-swift/78.md',
        '/swift/100-days-of-swift/79.md',
        '/swift/100-days-of-swift/80.md',
        '/swift/100-days-of-swift/81.md',
        '/swift/100-days-of-swift/82.md',
        '/swift/100-days-of-swift/83.md',
        '/swift/100-days-of-swift/84.md',
        '/swift/100-days-of-swift/85.md',
        '/swift/100-days-of-swift/86.md',
        '/swift/100-days-of-swift/87.md',
        '/swift/100-days-of-swift/88.md',
        '/swift/100-days-of-swift/89.md',
        '/swift/100-days-of-swift/90.md',
        '/swift/100-days-of-swift/91.md',
        '/swift/100-days-of-swift/92.md',
        '/swift/100-days-of-swift/93.md',
        '/swift/100-days-of-swift/94.md',
        '/swift/100-days-of-swift/95.md',
        '/swift/100-days-of-swift/96.md',
        '/swift/100-days-of-swift/97.md',
        '/swift/100-days-of-swift/98.md',
        '/swift/100-days-of-swift/99.md',
        '/swift/100-days-of-swift/100.md',
        '/swift/100-days-of-swift/101.md',
      ]
    }, {
      text: '100 Days of SwiftUI',
      collapsible: true,
      icon: 'fa-brands fa-swift',
      children: [
        '/swift/100-days-of-swiftui/README.md',
        '/swift/100-days-of-swiftui/01.md',
        '/swift/100-days-of-swiftui/02.md',
        '/swift/100-days-of-swiftui/03.md',
        '/swift/100-days-of-swiftui/04.md',
        '/swift/100-days-of-swiftui/05.md',
        '/swift/100-days-of-swiftui/06.md',
        '/swift/100-days-of-swiftui/07.md',
        '/swift/100-days-of-swiftui/08.md',
        '/swift/100-days-of-swiftui/09.md',
        '/swift/100-days-of-swiftui/10.md',
        '/swift/100-days-of-swiftui/11.md',
        '/swift/100-days-of-swiftui/12.md',
        '/swift/100-days-of-swiftui/13.md',
        '/swift/100-days-of-swiftui/14.md',
        '/swift/100-days-of-swiftui/15.md',
        '/swift/100-days-of-swiftui/16.md',
        '/swift/100-days-of-swiftui/17.md',
        '/swift/100-days-of-swiftui/18.md',
        '/swift/100-days-of-swiftui/19.md',
        '/swift/100-days-of-swiftui/20.md',
        '/swift/100-days-of-swiftui/21.md',
        '/swift/100-days-of-swiftui/22.md',
        '/swift/100-days-of-swiftui/23.md',
        '/swift/100-days-of-swiftui/24.md',
        '/swift/100-days-of-swiftui/25.md',
        '/swift/100-days-of-swiftui/26.md',
        '/swift/100-days-of-swiftui/27.md',
        '/swift/100-days-of-swiftui/28.md',
        '/swift/100-days-of-swiftui/29.md',
        '/swift/100-days-of-swiftui/30.md',
        '/swift/100-days-of-swiftui/31.md',
        '/swift/100-days-of-swiftui/32.md',
        '/swift/100-days-of-swiftui/33.md',
        '/swift/100-days-of-swiftui/34.md',
        '/swift/100-days-of-swiftui/35.md',
        '/swift/100-days-of-swiftui/36.md',
        '/swift/100-days-of-swiftui/37.md',
        '/swift/100-days-of-swiftui/38.md',
        '/swift/100-days-of-swiftui/39.md',
        '/swift/100-days-of-swiftui/40.md',
        '/swift/100-days-of-swiftui/41.md',
        '/swift/100-days-of-swiftui/42.md',
        '/swift/100-days-of-swiftui/43.md',
        '/swift/100-days-of-swiftui/44.md',
        '/swift/100-days-of-swiftui/45.md',
        '/swift/100-days-of-swiftui/46.md',
        '/swift/100-days-of-swiftui/47.md',
        '/swift/100-days-of-swiftui/48.md',
        '/swift/100-days-of-swiftui/49.md',
        '/swift/100-days-of-swiftui/50.md',
        '/swift/100-days-of-swiftui/51.md',
        '/swift/100-days-of-swiftui/52.md',
        '/swift/100-days-of-swiftui/53.md',
        '/swift/100-days-of-swiftui/54.md',
        '/swift/100-days-of-swiftui/55.md',
        '/swift/100-days-of-swiftui/56.md',
        '/swift/100-days-of-swiftui/57.md',
        '/swift/100-days-of-swiftui/58.md',
        '/swift/100-days-of-swiftui/59.md',
        '/swift/100-days-of-swiftui/60.md',
        '/swift/100-days-of-swiftui/61.md',
        '/swift/100-days-of-swiftui/62.md',
        '/swift/100-days-of-swiftui/63.md',
        '/swift/100-days-of-swiftui/64.md',
        '/swift/100-days-of-swiftui/65.md',
        '/swift/100-days-of-swiftui/66.md',
        '/swift/100-days-of-swiftui/67.md',
        '/swift/100-days-of-swiftui/68.md',
        '/swift/100-days-of-swiftui/69.md',
        '/swift/100-days-of-swiftui/70.md',
        '/swift/100-days-of-swiftui/71.md',
        '/swift/100-days-of-swiftui/72.md',
        '/swift/100-days-of-swiftui/73.md',
        '/swift/100-days-of-swiftui/74.md',
        '/swift/100-days-of-swiftui/75.md',
        '/swift/100-days-of-swiftui/76.md',
        '/swift/100-days-of-swiftui/77.md',
        '/swift/100-days-of-swiftui/78.md',
        '/swift/100-days-of-swiftui/79.md',
        '/swift/100-days-of-swiftui/80.md',
        '/swift/100-days-of-swiftui/81.md',
        '/swift/100-days-of-swiftui/82.md',
        '/swift/100-days-of-swiftui/83.md',
        '/swift/100-days-of-swiftui/84.md',
        '/swift/100-days-of-swiftui/85.md',
        '/swift/100-days-of-swiftui/85.md',
        '/swift/100-days-of-swiftui/87.md',
        '/swift/100-days-of-swiftui/88.md',
        '/swift/100-days-of-swiftui/89.md',
        '/swift/100-days-of-swiftui/90.md',
        '/swift/100-days-of-swiftui/91.md',
        '/swift/100-days-of-swiftui/92.md',
        '/swift/100-days-of-swiftui/93.md',
        '/swift/100-days-of-swiftui/94.md',
        '/swift/100-days-of-swiftui/95.md',
        '/swift/100-days-of-swiftui/96.md',
        '/swift/100-days-of-swiftui/97.md',
        '/swift/100-days-of-swiftui/98.md',
        '/swift/100-days-of-swiftui/99.md',
        '/swift/100-days-of-swiftui/100.md',
        '/swift/100-days-of-swiftui/101.md',
      ]
    }, {
      text: 'SwiftUI by Example',
      collapsible: true,
      icon: 'fa-brands fa-swift',
      children: [
        '/swift/swiftui-by-example/README.md',
        '/swift/swiftui-by-example/01-building-a-complete-project.md',
        '/swift/swiftui-by-example/02-working-with-static-text.md',
        '/swift/swiftui-by-example/03-images-shapes-and-media.md',
        '/swift/swiftui-by-example/04-view-layout.md',
        '/swift/swiftui-by-example/05-stacks-grids-scrollviews.md',
        '/swift/swiftui-by-example/06-user-interface-controls.md',
        '/swift/swiftui-by-example/07-responding-to-events.md',
        '/swift/swiftui-by-example/08-taps-and-gestures.md',
        '/swift/swiftui-by-example/09-advanced-state.md',
        '/swift/swiftui-by-example/10-lists.md',
        '/swift/swiftui-by-example/11-forms.md',
        '/swift/swiftui-by-example/12-containers.md',
        '/swift/swiftui-by-example/13-navigation.md',
        '/swift/swiftui-by-example/14-alerts-and-menus.md',
        '/swift/swiftui-by-example/15-presenting-views.md',
        '/swift/swiftui-by-example/16-transforming-views.md',
        '/swift/swiftui-by-example/17-drawing.md',
      ]
    }, {
      text: 'Kodeco - Swift',
      collapsible: true,
      icon: 'fa-brands fa-swift',
      children: [
        '/swift/kodeco/README.md',
        '/swift/kodeco/6398124-swiftui-tutorial-for-ios-creating-charts.md',
        '/swift/kodeco/6334294-my-app-crashed-now-what.md',
        '/swift/kodeco/6587213-alamofire-5-tutorial-for-ios-getting-started.md',        
        '/swift/kodeco/6620276-sqlite-with-swift-tutorial-getting-started.md',
        '/swift/kodeco/6747815-uigesturerecognizer-tutorial-getting-started.md',
        '/swift/kodeco/6827616-ios-accessibility-getting-started.md',
        '/swift/kodeco/6742901-protocol-oriented-programming-tutorial-in-swift-5-1-getting-started.md',
        '/swift/kodeco/7076593-cocoapods-tutorial-for-swift-getting-started.md',
        '/swift/kodeco/7181017-unsafe-swift-using-pointers-and-interacting-with-c.md',
      ]
    }, {
      text: 'OSX 구조를 이해하면서 배우는 Objective-C',
      collapsible: true,
      icon: 'fas fa-landmark',
      children: [
        '/swift/shuokai-objc/README.md',
        '/swift/shuokai-objc/01.md',
        '/swift/shuokai-objc/02.md',
        '/swift/shuokai-objc/03.md',
        '/swift/shuokai-objc/04.md',
        '/swift/shuokai-objc/05.md',
        '/swift/shuokai-objc/06.md',
        '/swift/shuokai-objc/07.md',
        '/swift/shuokai-objc/08.md',
        '/swift/shuokai-objc/09.md',
        '/swift/shuokai-objc/10.md',
        '/swift/shuokai-objc/11.md',
        '/swift/shuokai-objc/12.md',
        '/swift/shuokai-objc/13.md',
        '/swift/shuokai-objc/14.md',
        '/swift/shuokai-objc/15.md',
        '/swift/shuokai-objc/16.md',
        '/swift/shuokai-objc/17.md',
        '/swift/shuokai-objc/18.md',
        '/swift/shuokai-objc/19.md',
        '/swift/shuokai-objc/20.md',
        '/swift/shuokai-objc/21.md',
      ]
    }
  ], '/java/' : [
    {
      text: 'Java',
      icon: 'fa-brands fa-java',
      children: [ '/java/README.md' ]
    }, {
      text: 'Java8 in Action',
      icon: 'fa-brands fa-java',
      collapsible: true,
      children: [
        '/java/java-8-in-action/README.md',
        '/java/java-8-in-action/1.md',
        '/java/java-8-in-action/2-1.md',
        '/java/java-8-in-action/2-2.md',
        '/java/java-8-in-action/3-1.md',
      ]
    }, {
      text: 'Effective Java',
      collapsible: true,
      icon: 'fa-brands fa-java',
      children: [
        '/java/effective-java/README.md',
        '/java/effective-java/01-creating-and-destroying-objects.md',
        '/java/effective-java/02-methods-common-to-all-objects.md',
        '/java/effective-java/03-classes-and-interfaces.md',
        '/java/effective-java/04-generics.md',
        '/java/effective-java/05-enums-and-annotations.md',
        '/java/effective-java/06-lambda-and-stream.md',
        '/java/effective-java/07-methods.md',
        '/java/effective-java/08-general-programming.md',
        '/java/effective-java/09-exceptions.md',
        '/java/effective-java/10-concurrency.md',
        '/java/effective-java/11-serialization.md'
      ]
    }, {
      text: 'Kodeco - Android & Kotlin',
      collapsible: true,
      icon: 'fa-brands fa-android',
      children: [
        '/java/kodeco/README.md',
        '/java/kodeco/247-react-native-tutorial-building-android-apps-with-javascript.md',
        '/java/kodeco/249-gradle-tutorial-for-android-getting-started.md',
        '/java/kodeco/254-getting-started-with-android-wear-with-kotlin.md',
        '/java/kodeco/262-dependency-injection-in-android-with-dagger-2-and-kotlin.md',
        '/java/kodeco/272-intermediate-recyclerview-tutorial-with-kotlin.md',
        '/java/kodeco/853-couchbase-tutorial-for-android-getting-started.md',
        '/java/kodeco/523-augmented-reality-in-android-with-google-s-face-api.md',
        '/java/kodeco/324-viewpager-tutorial-getting-started-in-kotlin.md',
        '/java/kodeco/30067669-documenting-kotlin-code-for-android-using-kdoc-and-dokka.md',
        '/java/kodeco/31290959-kotlin-sequences-getting-started.md',
      ]
    }, {
      text: 'Jump to Spring Boot',
      collapsible: true,
      icon: 'fa-brands fa-envira',
      children: [
        '/java/jump-to-spring-boot/README.md',
        '/java/jump-to-spring-boot/01.md',
        '/java/jump-to-spring-boot/02.md',
        '/java/jump-to-spring-boot/02A.md',
        '/java/jump-to-spring-boot/02B.md',
        '/java/jump-to-spring-boot/02C.md',
        '/java/jump-to-spring-boot/02D.md',
        '/java/jump-to-spring-boot/02E.md',
        '/java/jump-to-spring-boot/02F.md',
        '/java/jump-to-spring-boot/02G.md',
        '/java/jump-to-spring-boot/02H.md',
        '/java/jump-to-spring-boot/02I.md',
        '/java/jump-to-spring-boot/02J.md',
        '/java/jump-to-spring-boot/02K.md',
        '/java/jump-to-spring-boot/02L.md',
        '/java/jump-to-spring-boot/02M.md',
        '/java/jump-to-spring-boot/02N.md',
        '/java/jump-to-spring-boot/02O.md',
        '/java/jump-to-spring-boot/02P.md',
        '/java/jump-to-spring-boot/03.md',
        '/java/jump-to-spring-boot/03A.md',
        '/java/jump-to-spring-boot/03B.md',
        '/java/jump-to-spring-boot/03C.md',
        '/java/jump-to-spring-boot/03D.md',
        '/java/jump-to-spring-boot/03E.md',
        '/java/jump-to-spring-boot/03F.md',
        '/java/jump-to-spring-boot/03G.md',
        '/java/jump-to-spring-boot/03H.md',
        '/java/jump-to-spring-boot/03I.md',
        '/java/jump-to-spring-boot/03J.md',
        '/java/jump-to-spring-boot/03K.md',
        '/java/jump-to-spring-boot/03L.md',
        '/java/jump-to-spring-boot/03M.md',
        '/java/jump-to-spring-boot/03N.md',
        '/java/jump-to-spring-boot/03O.md',
        '/java/jump-to-spring-boot/04.md',
        '/java/jump-to-spring-boot/04A.md',
        '/java/jump-to-spring-boot/04B.md',
        '/java/jump-to-spring-boot/04C.md',
        '/java/jump-to-spring-boot/04D.md',
        '/java/jump-to-spring-boot/04E.md',
        '/java/jump-to-spring-boot/04F.md',
        '/java/jump-to-spring-boot/04G.md',
        '/java/jump-to-spring-boot/04H.md',
        '/java/jump-to-spring-boot/04I.md',
        '/java/jump-to-spring-boot/04J.md',
        '/java/jump-to-spring-boot/04K.md',
        '/java/jump-to-spring-boot/04L.md',
        '/java/jump-to-spring-boot/a.md',
      ]
    }, {
      text: 'Java Web App with Quarkus and JPAStreamer',
      collapsible: true,
      icon: 'iconfont icon-java',
      children: [
        '/java/freecodecamp-quarkus-jpastreamer/README.md',
        '/java/freecodecamp-quarkus-jpastreamer/01.md',
        '/java/freecodecamp-quarkus-jpastreamer/02.md',
        '/java/freecodecamp-quarkus-jpastreamer/03.md',
        '/java/freecodecamp-quarkus-jpastreamer/04.md',
        '/java/freecodecamp-quarkus-jpastreamer/05.md',
      ]
    },
  ], '/js/': [
    {
      text: 'JavaScript',
      icon: 'fa-brands fa-js',
      children: [ '/js/README.md' ]
    }, {
      text: 'Learn Typescript',
      icon: 'iconfont icon-typescript',
      collapsible: true,
      children: [
        '/js/learn-ts/README.md',
        '/js/learn-ts/advanced/01.md',
        '/js/learn-ts/advanced/02.md',
        '/js/learn-ts/advanced/03.md',
        '/js/learn-ts/advanced/04.md',
        '/js/learn-ts/advanced/05.md',
        '/js/learn-ts/advanced/06.md',
        '/js/learn-ts/advanced/07.md',
        '/js/learn-ts/advanced/08.md',
        '/js/learn-ts/advanced/09.md',
        '/js/learn-ts/advanced/10.md',
        '/js/learn-ts/advanced/11.md',
        '/js/learn-ts/advanced/12.md',
        '/js/learn-ts/advanced/13.md',
        '/js/learn-ts/advanced/14.md',
        '/js/learn-ts/advanced/15.md',
        '/js/learn-ts/advanced/16.md',
        '/js/learn-ts/advanced/17.md',
        '/js/learn-ts/advanced/18.md',
      ]
    }, {
      text: 'Must Know JavaScript API',
      collapsible: true,
      icon: 'fa-brands fa-js',
      children: [
        '/js/must-know-javascript-api/README.md',
        '/js/must-know-javascript-api/page-visibility.md',
        '/js/must-know-javascript-api/broadcast-channel.md',
        '/js/must-know-javascript-api/resize-observer.md',
        '/js/must-know-javascript-api/beacon.md',
        '/js/must-know-javascript-api/clipboard.md',
        '/js/must-know-javascript-api/fetch.md'
      ]
    }, {
      text: 'Eloquent Javascript',
      collapsible: true,
      icon: 'fa-brands fa-js',
      children: [
        '/js/eloquent-javascript/README.md',
        '/js/eloquent-javascript/00.md',
        '/js/eloquent-javascript/01.md',
        '/js/eloquent-javascript/02.md',
        '/js/eloquent-javascript/03.md',
        '/js/eloquent-javascript/04.md',
        '/js/eloquent-javascript/05.md',
        '/js/eloquent-javascript/06.md',
        '/js/eloquent-javascript/07.md',
        '/js/eloquent-javascript/08.md',
        '/js/eloquent-javascript/09.md',
        '/js/eloquent-javascript/10.md',
        '/js/eloquent-javascript/11.md',
        '/js/eloquent-javascript/12.md',
        '/js/eloquent-javascript/13.md',
        '/js/eloquent-javascript/14.md',
        '/js/eloquent-javascript/15.md',
        '/js/eloquent-javascript/16.md',
        '/js/eloquent-javascript/17.md',
        '/js/eloquent-javascript/18.md',
        '/js/eloquent-javascript/19.md',
        '/js/eloquent-javascript/20.md',
        '/js/eloquent-javascript/21.md',
      ]
    }
  ], '/python/': [
    {
      text: 'Python',
      icon: 'fa-brands fa-python',
      children: [ '/python/README.md' ]
    }, {
      text: 'Finance with Python',
      collapsible: true,
      icon: 'fa-brands fa-python',
      children: [
        '/python/finance-w-python/README.md',
        '/python/finance-w-python/01.md',
        '/python/finance-w-python/02.md',
        '/python/finance-w-python/03.md',
        '/python/finance-w-python/04.md',
        '/python/finance-w-python/05.md',
        '/python/finance-w-python/06.md',
        '/python/finance-w-python/07.md',
        '/python/finance-w-python/08.md',
        '/python/finance-w-python/09.md', 
        '/python/finance-w-python/10.md', 
        '/python/finance-w-python/11.md', 
        '/python/finance-w-python/12.md', 
      ]
    }, {
      text: '사장님 몰래 하는 파이썬 업무자동화 (들키면 일 많아짐)',
      collapsible: true,
      icon: 'fa-brands fa-python',
      children: [
        '/python/rpa-excel/README.md',
        '/python/rpa-excel/01.md',
        '/python/rpa-excel/02a.md',
        '/python/rpa-excel/02b.md',
        '/python/rpa-excel/02c.md',
        '/python/rpa-excel/02d.md',
        '/python/rpa-excel/02e.md',
        '/python/rpa-excel/02f.md',
        '/python/rpa-excel/02g.md',
        '/python/rpa-excel/02h.md',
        '/python/rpa-excel/02i.md',
        '/python/rpa-excel/03.md',
      ]
    },  {
      text: 'OpenCV – Python 고급 기법 프로그래밍',
      collapsible: true,
      icon: 'fa-brands fa-python',
      children: [
        '/python/opencv-advacned/README.md',
        '/python/opencv-advacned/00.md',
        '/python/opencv-advacned/01.md',
        '/python/opencv-advacned/02.md',
      ],
    }
  ], '/rust/': [
    {
      text: 'Rust',
      icon: 'fa-brands fa-rust',
      children: [ '/rust/README.md' ]
    }, {
      text: 'freecodecamp.org - Rust by Practice',
      collapsible: true,
      icon: 'fa-brands fa-rust',
      children: [
        '/rust/freecodecamp-rust-by-practice/README.md',
        '/rust/freecodecamp-rust-by-practice/01-elegant-code-base.md',
        '/rust/freecodecamp-rust-by-practice/02-variables.md',
        '/rust/freecodecamp-rust-by-practice/03-basic-types.md',
        '/rust/freecodecamp-rust-by-practice/04-ownership.md',
        '/rust/freecodecamp-rust-by-practice/05-compound-types.md',
        '/rust/freecodecamp-rust-by-practice/06-flow-contro.md',
        '/rust/freecodecamp-rust-by-practice/07-pattern-match.md',
        '/rust/freecodecamp-rust-by-practice/08-method.md',
        '/rust/freecodecamp-rust-by-practice/09-generics-traits.md',
        '/rust/freecodecamp-rust-by-practice/10-collections.md',
        '/rust/freecodecamp-rust-by-practice/11-type-conversions.md',
        '/rust/freecodecamp-rust-by-practice/12-result-panic.md',
        '/rust/freecodecamp-rust-by-practice/13-crate-module.md',
        '/rust/freecodecamp-rust-by-practice/14-comments-docs.md',
        '/rust/freecodecamp-rust-by-practice/15-formatted-output.md',
        '/rust/freecodecamp-rust-by-practice/16-lifetime.md',
        '/rust/freecodecamp-rust-by-practice/17-functional-programing.md',
        '/rust/freecodecamp-rust-by-practice/18-newtype-sized.md',
        '/rust/freecodecamp-rust-by-practice/19-smart-pointers.md',
        '/rust/freecodecamp-rust-by-practice/20-weak.md',
        '/rust/freecodecamp-rust-by-practice/21-self-referential.md',
        '/rust/freecodecamp-rust-by-practice/22-threads.md',
        '/rust/freecodecamp-rust-by-practice/23-global-variables.md',
        '/rust/freecodecamp-rust-by-practice/24-errors.md',
        '/rust/freecodecamp-rust-by-practice/25-unsafe.md',
        '/rust/freecodecamp-rust-by-practice/26-macro.md',
        '/rust/freecodecamp-rust-by-practice/27-tests.md',
        '/rust/freecodecamp-rust-by-practice/28-async.md',
        '/rust/freecodecamp-rust-by-practice/29-std.md',
        '/rust/freecodecamp-rust-by-practice/30-fight-compiler.md',
      ]
    }, {
      text: 'Wasm by Example',
      collapsible: true,
      icon: 'fa-brands fa-rust',
      children: [
        '/rust/wasm-by-example/README.md',
        '/rust/wasm-by-example/01-concepts.md',
        '/rust/wasm-by-example/02-applying-the-concepts.md',
        '/rust/wasm-by-example/03-ecosystem-tools-and-language-features.md',
        '/rust/wasm-by-example/04-webassembly-outside-of-the-browser.md',
      ]
    }, {
      text: 'Rust to Assembly',
      collapsible: true,
      icon: 'fa-brands fa-rust',
      children: [
        '/rust/eventhelix-rust-to-assembly/README.md',
        '/rust/eventhelix-rust-to-assembly/rust-enum-and-match-representation-in-assembly.md',
        '/rust/eventhelix-rust-to-assembly/assembly-code-generated-when-self-is-passed-by-value-reference-or-as-a-smart-pointer.md',
        '/rust/eventhelix-rust-to-assembly/mapping-arrays-tuples-box-and-option-to-assembly.md',
        '/rust/eventhelix-rust-to-assembly/rust-to-assembly-vector-iteration.md'
      ]
    }, 
  ], '/cpp/':  [ 
    {
      text: 'Cpp',
      icon: 'fas fa-dice-two',
      children: [ '/cpp/README.md' ]
    }, {
      text: 'Algorithms for Competitive Programming',
      collapsible: true,
      icon: 'fas fa-dice-two',
      children: [ 
        '/cpp/algorithms-for-competitive-programming/README.md',
        '/cpp/algorithms-for-competitive-programming/01-algebra/01A.md',
        '/cpp/algorithms-for-competitive-programming/01-algebra/01B.md',
        '/cpp/algorithms-for-competitive-programming/01-algebra/01C.md',
        '/cpp/algorithms-for-competitive-programming/01-algebra/01D.md',
        '/cpp/algorithms-for-competitive-programming/01-algebra/01E.md',
        '/cpp/algorithms-for-competitive-programming/01-algebra/01F.md',
        '/cpp/algorithms-for-competitive-programming/02-data-structures/02A.md',
        '/cpp/algorithms-for-competitive-programming/02-data-structures/02B.md',
        '/cpp/algorithms-for-competitive-programming/02-data-structures/02C.md',
        '/cpp/algorithms-for-competitive-programming/03-dynamic-programming/03A.md',
        '/cpp/algorithms-for-competitive-programming/03-dynamic-programming/03B.md',
        '/cpp/algorithms-for-competitive-programming/03-dynamic-programming/03C.md',
        '/cpp/algorithms-for-competitive-programming/04-string-processing/04A.md',
        '/cpp/algorithms-for-competitive-programming/04-string-processing/04B.md',
        '/cpp/algorithms-for-competitive-programming/04-string-processing/04C.md',
        '/cpp/algorithms-for-competitive-programming/05-linear-algebra/05A.md',
        '/cpp/algorithms-for-competitive-programming/06-combinatorics/06A.md',
        '/cpp/algorithms-for-competitive-programming/06-combinatorics/06B.md',
        '/cpp/algorithms-for-competitive-programming/06-combinatorics/06C.md',
        '/cpp/algorithms-for-competitive-programming/07-numerical-methods/07A.md',
        '/cpp/algorithms-for-competitive-programming/07-numerical-methods/07B.md',
        '/cpp/algorithms-for-competitive-programming/08-geometry/08A.md',
        '/cpp/algorithms-for-competitive-programming/08-geometry/08B.md',
        '/cpp/algorithms-for-competitive-programming/08-geometry/08C.md',
        '/cpp/algorithms-for-competitive-programming/08-geometry/08D.md',
        '/cpp/algorithms-for-competitive-programming/08-geometry/08E.md',
        '/cpp/algorithms-for-competitive-programming/08-geometry/08F.md',
      ]
    }
  ], '/ruby/': [
    {
      text: 'Ruby',
      icon: 'fas fa-gem',
      children: [ '/ruby/README.md' ]
    }, {
      text: 'Jets - Learning Content',
      collapsible: true,
      icon: 'fas fa-gem',
      children: [
        '/ruby/rubyonjets-learning-content/README.md',
        '/ruby/rubyonjets-learning-content/20190204-aws-lambda-function-jets-introductory-series-part-1.md',
        '/ruby/rubyonjets-learning-content/20190205-api-gateway-jets-introductory-series-part-2.md',
        '/ruby/rubyonjets-learning-content/20190206-cloudwatch-event-rule-jets-introductory-series-part-3.md',
        '/ruby/rubyonjets-learning-content/20190211-hello-world-examples-jets-introductory-series-part-4',
        '/ruby/rubyonjets-learning-content/20180907-jets-tutorial-crud-app-introduction-part-1.md',
        '/ruby/rubyonjets-learning-content/20180908-jets-tutorial-deploy-to-aws-lambda-part-2.md',
        '/ruby/rubyonjets-learning-content/20180909-jets-tutorial-debugging-logs-part-3.md',
        '/ruby/rubyonjets-learning-content/20180910-jets-tutorial-background-jobs-part-4.md',
        '/ruby/rubyonjets-learning-content/20180911-jets-tutorial-iam-policies-part-5.md',
        '/ruby/rubyonjets-learning-content/20180912-jets-tutorial-function-properties-part-6.md',
        '/ruby/rubyonjets-learning-content/20180913-jets-tutorial-extra-environments-part-7.md',
        '/ruby/rubyonjets-learning-content/20180926-jets-tutorial-different-environments-part-8.md',
        '/ruby/rubyonjets-learning-content/20180927-jets-tutorial-polymorphic-support-part-9.md',
        '/ruby/rubyonjets-learning-content/20181112-jets-tutorial-jets-delete.md',
        '/ruby/rubyonjets-learning-content/20180818-introducing-jets-a-ruby-serverless-framework.md',
        '/ruby/rubyonjets-learning-content/20181212-official-aws-ruby-support-for-jets-serverless-framework.md',
        '/ruby/rubyonjets-learning-content/20181213-jets-image-upload-carrierwave-tutorial-binary-support.md',
        '/ruby/rubyonjets-learning-content/20190113-build-an-api-service-with-jets-ruby-serverless-framework.md',
        '/ruby/rubyonjets-learning-content/20190114-serverless-slack-commands-with-ruby.md',
        '/ruby/rubyonjets-learning-content/20181221-jets-afterburner-serverless-rails-on-aws-lambda-in-5-minutes.md',
      ]
    }, 
  ], '/haskell/': [
    {
      text: '🐑Haskell',
      children: [ '/haskell/README.md' ]

    }, {
      text: '🐑Megaparsec tutorial',
      collapsible: true,
      children: [
        '/haskell/megaparsec/README.md',
        '/haskell/megaparsec/01.md',
        '/haskell/megaparsec/02.md',
        '/haskell/megaparsec/03.md',
        '/haskell/megaparsec/04.md',
        '/haskell/megaparsec/05.md',
        '/haskell/megaparsec/06.md',
        '/haskell/megaparsec/07.md',
        '/haskell/megaparsec/08.md',
        '/haskell/megaparsec/09.md',
        '/haskell/megaparsec/10.md',
        '/haskell/megaparsec/11.md',
        '/haskell/megaparsec/12.md',
        '/haskell/megaparsec/13.md',
        '/haskell/megaparsec/14.md',
        '/haskell/megaparsec/15.md',
        '/haskell/megaparsec/16.md',
        '/haskell/megaparsec/17.md',
        '/haskell/megaparsec/18.md',
      ]
    }, {
      text: '🐑Template Haskell tutorial',
      collapsible: true,
      children: [
        '/haskell/template-haskell/README.md',
        '/haskell/template-haskell/01.md',
        '/haskell/template-haskell/02.md',
        '/haskell/template-haskell/03.md',
        '/haskell/template-haskell/04.md',
        '/haskell/template-haskell/05.md',
        '/haskell/template-haskell/06.md',
        '/haskell/template-haskell/07.md',
        '/haskell/template-haskell/08.md',
        '/haskell/template-haskell/09.md',
        '/haskell/template-haskell/10.md',
        '/haskell/template-haskell/11.md',
        '/haskell/template-haskell/12.md',
        '/haskell/template-haskell/13.md',
        '/haskell/template-haskell/14.md',
        '/haskell/template-haskell/15.md',
      ]
    }
  ], '/devops/': [
    {
      text: 'DevOps',
      icon: 'fas fa-cubes-stacked',
      children: [ '/devops/README.md' ]
    }, {
      text: 'Red Hat Container Tools',
      collapsible: true,
      icon: 'fa-brands fa-redhat',
      children: [
        '/devops/red-hat-container-tools/README.md',
        '/devops/red-hat-container-tools/01.md',
        '/devops/red-hat-container-tools/02.md',
        '/devops/red-hat-container-tools/03.md',
        '/devops/red-hat-container-tools/04.md',
        '/devops/red-hat-container-tools/05.md',
        '/devops/red-hat-container-tools/06.md',
        '/devops/red-hat-container-tools/07.md',
        '/devops/red-hat-container-tools/08.md'
      ]
    }, {
      text: 'Containerize Your Application With Buildah And Podman',
      collapsible: true,
      icon: 'fa-brands fa-redhat',
      children: [
        '/devops/red-hat-containerize-your-application-w-buildah-and-podman/README.md',
        '/devops/red-hat-containerize-your-application-w-buildah-and-podman/01.md',
        '/devops/red-hat-containerize-your-application-w-buildah-and-podman/02.md',
        '/devops/red-hat-containerize-your-application-w-buildah-and-podman/03.md'
      ]
    }, {
      text: 'freecodecamp.org - DevOps with GitLab CI',
      collapsible: true,
      icon: 'fa-brands fa-gitlab',
      children: [
        '/devops/freecodecamp-gitlab-ci/README.md',
        '/devops/freecodecamp-gitlab-ci/1.md',
        '/devops/freecodecamp-gitlab-ci/2.md',
        '/devops/freecodecamp-gitlab-ci/3.md',
        '/devops/freecodecamp-gitlab-ci/4.md',
        '/devops/freecodecamp-gitlab-ci/5.md',
      ]
    }, {
      text: '☸DigitalOcean - Kubernetes',
      collapsible: true,
      children: [
        '/devops/digitalocean-kubernetes/README.md',
        '/devops/digitalocean-kubernetes/2022/20221216-how-to-run-serverless-workloads-with-knative-on-digitalocean-kubernetes.md',
        '/devops/digitalocean-kubernetes/2022/20221118-how-to-secure-your-site-in-kubernetes-with-cert-manager-traefik-and-let-s-encrypt.md',
      ]
    }, {
      text: '아마존 웹 서비스를 다루는 기술 - 실무에서 필요한 AWS 클라우드의 모든 것!',
      collapsible: true,
      icon: 'fa-brands fa-aws',
      children: [
        '/devops/art-of-aws/README.md',
        '/devops/art-of-aws/01.md',
        '/devops/art-of-aws/02.md',
        '/devops/art-of-aws/03.md',
        '/devops/art-of-aws/04.md',
        '/devops/art-of-aws/05.md',
        '/devops/art-of-aws/06.md',
        '/devops/art-of-aws/07.md',
        '/devops/art-of-aws/08.md',
        '/devops/art-of-aws/09.md',
        '/devops/art-of-aws/10.md',
        '/devops/art-of-aws/11.md',
        '/devops/art-of-aws/12.md',
        '/devops/art-of-aws/13.md',
        '/devops/art-of-aws/14.md',
        '/devops/art-of-aws/15.md',
        '/devops/art-of-aws/16.md',
        '/devops/art-of-aws/17.md',
        '/devops/art-of-aws/18.md',
        '/devops/art-of-aws/19.md',
        '/devops/art-of-aws/20.md',
        '/devops/art-of-aws/21.md',
        '/devops/art-of-aws/22.md',
        '/devops/art-of-aws/23.md',
        '/devops/art-of-aws/24.md',
        '/devops/art-of-aws/25.md',
        '/devops/art-of-aws/26.md',
        '/devops/art-of-aws/27.md',
        '/devops/art-of-aws/28.md',
        '/devops/art-of-aws/29.md',
        '/devops/art-of-aws/30.md',
        '/devops/art-of-aws/31.md',
        '/devops/art-of-aws/32.md',
        '/devops/art-of-aws/33.md',
        '/devops/art-of-aws/a.md',        
      ]
    }, {
      text: 'Linux Journey',
      collapsible: true,
      icon: 'fa-brands fa-linux',
      children: [
        '/devops/linux-journey/README.md',
        '/devops/linux-journey/01-grasshopper/01a-getting-started.md',
        '/devops/linux-journey/01-grasshopper/01b-command-line.md',
        '/devops/linux-journey/01-grasshopper/01c-text-fu.md',
        '/devops/linux-journey/01-grasshopper/01d-advanced-text-fu.md',
        '/devops/linux-journey/01-grasshopper/01e-user-management.md',
        '/devops/linux-journey/01-grasshopper/01f-permissions.md',
        '/devops/linux-journey/01-grasshopper/01g-processes.md',
        '/devops/linux-journey/01-grasshopper/01h-packages.md',
        '/devops/linux-journey/02-journeyman/02a-devices.md',
        '/devops/linux-journey/02-journeyman/02b-the-filesystem.md',
        '/devops/linux-journey/02-journeyman/02c-boot-the-system.md',
        '/devops/linux-journey/02-journeyman/02d-kernel.md',
        '/devops/linux-journey/02-journeyman/02e-init.md',
        '/devops/linux-journey/02-journeyman/02f-process-utilization.md',
        '/devops/linux-journey/02-journeyman/02g-logging.md',
        '/devops/linux-journey/03-networking-nomad/03a-network-sharing.md',
        '/devops/linux-journey/03-networking-nomad/03b-network-basics.md',
        '/devops/linux-journey/03-networking-nomad/03c-subnetting.md',
        '/devops/linux-journey/03-networking-nomad/03d-routing.md',
        '/devops/linux-journey/03-networking-nomad/03e-network-config.md',
        '/devops/linux-journey/03-networking-nomad/03f-troubleshooting.md',
        '/devops/linux-journey/03-networking-nomad/03g-dns.md'
      ]
    }, 
  ], '/misc/': [
    {
      text: 'Misc.',
      icon: 'fas fa-object-group',
      children: [ '/misc/README.md' ]
    }, {
      text: 'Colt Steele - Mastering CSS Grid',
      collapsible: true,
      icon: 'fa-brands fa-css3-alt',
      children: [
        '/misc/colt-steele-mastering-css-grid/README.md',
        '/misc/colt-steele-mastering-css-grid/01-css-grid-basics',
        '/misc/colt-steele-mastering-css-grid/02-units-and-utilities',
        '/misc/colt-steele-mastering-css-grid/03-positioning-elements-by-lines',
        '/misc/colt-steele-mastering-css-grid/04-grid-areas',
        '/misc/colt-steele-mastering-css-grid/05-the-implicit-grid',
        '/misc/colt-steele-mastering-css-grid/06-creating-responsive-grids',
        '/misc/colt-steele-mastering-css-grid/07-building-an-example-layout',
      ]
    }, {
      text: 'Microsoft - Generative AI for Beginners',
      collapsible: true,
      icon: 'fas fa-brain',
      children: [
        '/misc/llm-generative-ai-for-beginners/README.md',
        '/misc/llm-generative-ai-for-beginners/00-course-setup.md',
        '/misc/llm-generative-ai-for-beginners/01-introduction-to-genai.md',
        '/misc/llm-generative-ai-for-beginners/02-exploring-and-comparing-different-llms.md',
      ]
    }, {
      text: "DB Server 성능 향상 분석 및 튜닝 전문가 향상과정",
      collapsible: true,
      icon: 'fas fa-database',
      children: [
        '/misc/oracle-sql-db-tuning/README.md',
        '/misc/oracle-sql-db-tuning/01a.md',
        '/misc/oracle-sql-db-tuning/01b.md',
        '/misc/oracle-sql-db-tuning/01c.md',
        '/misc/oracle-sql-db-tuning/01d.md',
        '/misc/oracle-sql-db-tuning/02a.md',
        '/misc/oracle-sql-db-tuning/03a.md',
        '/misc/oracle-sql-db-tuning/03b.md',
        '/misc/oracle-sql-db-tuning/03c.md',
      ],
    }
  ]
});